"""
Script to calculate macroscopic pore metrics from Excel analysis reports.

This script processes combined analysis reports generated by the batch
quantitative analysis pipeline and calculates aggregate macroscopic
metrics for each material, outputting a single summary Excel file.

Usage:
    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir

    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir \
        --output-file /custom/path/macroscopic_metrics.xlsx
"""
import argparse
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.stats import entropy, skew

from materials_vision.logging_config import setup_logging

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed command line arguments containing:
        - input_dir: Path to directory containing material subdirectories
        - output_file: Path for output Excel file (optional)
        - verbose: Enable debug logging
    """
    parser = argparse.ArgumentParser(
        description=(
            "Calculate macroscopic pore metrics from analysis reports"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help=(
            "Path to directory containing material subdirectories "
            "with analysis reports"
        )
    )

    parser.add_argument(
        "--output-file",
        type=str,
        default=None,
        help=(
            "Path for output Excel file. Default: "
            "<input_dir>/macroscopic_pore_metrics.xlsx"
        )
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose (DEBUG) logging"
    )

    return parser.parse_args()


def find_analysis_reports(input_dir: Path) -> List[Tuple[str, Path]]:
    """
    Find all combined analysis report Excel files in the input directory.

    Searches for files matching the pattern:
    <input_dir>/<material_name>/reports/*_combined_analysis_report.xlsx

    Parameters
    ----------
    input_dir : Path
        Parent directory containing material subdirectories

    Returns
    -------
    List[Tuple[str, Path]]
        List of tuples containing (material_name, report_path)

    Raises
    ------
    FileNotFoundError
        If input_dir does not exist
    """
    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    reports = []

    subdirs = [
        d for d in input_dir.iterdir()
        if d.is_dir() and not d.name.startswith('.')
    ]
    subdirs.sort()

    for subdir in subdirs:
        reports_dir = subdir / "reports"
        if not reports_dir.exists():
            logger.debug(f"No reports directory in: {subdir.name}")
            continue

        report_files = [
            f for f in reports_dir.glob("*_combined_analysis_report.xlsx")
            if not f.name.startswith('.')
        ]

        if not report_files:
            logger.debug(
                f"No analysis report found in: {reports_dir}"
            )
            continue

        report_path = report_files[0]
        material_name = subdir.name
        reports.append((material_name, report_path))
        logger.info(f"Found report for material: {material_name}")

    return reports


def read_individual_pores_sheet(
    report_path: Path
) -> Optional[pd.DataFrame]:
    """
    Read the Individual_Pores sheet from an analysis report.

    Parameters
    ----------
    report_path : Path
        Path to the Excel analysis report

    Returns
    -------
    Optional[pd.DataFrame]
        DataFrame with individual pore data, or None if reading fails

    Notes
    -----
    Required columns: equivalent_diameter, aspect_ratio, circularity,
    ellipse_angle, coordination_number
    """
    required_columns = [
        'equivalent_diameter',
        'aspect_ratio',
        'circularity',
        'ellipse_angle',
        'coordination_number'
    ]

    try:
        df = pd.read_excel(
            report_path,
            sheet_name="Individual_Pores",
            engine="openpyxl"
        )
    except Exception as e:
        logger.error(f"Failed to read {report_path}: {e}")
        return None

    if df.empty:
        logger.warning(f"No pore data in {report_path}")
        return None

    missing_cols = [c for c in required_columns if c not in df.columns]
    if missing_cols:
        logger.warning(
            f"Missing columns in {report_path.name}: {missing_cols}. "
            "Skipping this material."
        )
        return None

    return df


def calculate_centered_entropy(
    angles: np.ndarray,
    num_bins: int = 18
) -> float:
    """
    Calculate normalized entropy of orientation angles.

    Centers the angle distribution around its mean direction before
    computing entropy, providing a rotation-invariant measure of
    orientation uniformity.

    Parameters
    ----------
    angles : np.ndarray
        Array of orientation angles in degrees (0-180)
    num_bins : int, optional
        Number of histogram bins for entropy calculation (default: 18)

    Returns
    -------
    float
        Normalized entropy value between 0 and 1, where:
        - 0 indicates perfect alignment (all angles identical)
        - 1 indicates uniform distribution (isotropic)

    Notes
    -----
    The function uses circular statistics to handle the periodic nature
    of orientation data. Angles are doubled before averaging to account
    for the 180-degree symmetry of ellipse orientations.

    Formula for normalization: H_norm = H / H_max
    where H_max = ln(num_bins) for uniform distribution
    """
    angles = np.array(angles)

    # Handle NaN values
    angles = angles[~np.isnan(angles)]
    if len(angles) == 0:
        return np.nan

    # Convert to radians and double (orientation is pi-periodic)
    angles_rad = np.deg2rad(angles) * 2

    # Calculate mean direction using circular statistics
    sin_sum = np.sum(np.sin(angles_rad))
    cos_sum = np.sum(np.cos(angles_rad))
    mean_angle = np.rad2deg(np.arctan2(sin_sum, cos_sum)) / 2

    # Center distribution around mean (shift so mean is at 90 degrees)
    shift = 90 - mean_angle
    angles_shifted = (angles + shift) % 180

    # Calculate histogram and entropy
    counts, _ = np.histogram(angles_shifted, bins=num_bins, range=(0, 180))
    if counts.sum() == 0:
        return 0.0

    probs = counts / counts.sum()
    shannon_entropy = entropy(probs)  # Uses natural log by default
    max_entropy = np.log(num_bins)

    return shannon_entropy / max_entropy


def calculate_size_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate size-related metrics from equivalent diameter.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'equivalent_diameter' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - size_mean: Mean equivalent diameter
        - size_median: Median equivalent diameter
        - size_d10: 10th percentile
        - size_d90: 90th percentile
        - size_span: (D90 - D10) / Median
        - size_skewness: Skewness of size distribution

    Notes
    -----
    Span formula: (D90 - D10) / D50
    This is a common metric in particle size analysis describing
    the width of the size distribution relative to the median.
    """
    diameters = df['equivalent_diameter'].dropna()

    if len(diameters) == 0:
        logger.warning("No valid diameter values")
        return {
            'size_mean': np.nan,
            'size_median': np.nan,
            'size_d10': np.nan,
            'size_d90': np.nan,
            'size_span': np.nan,
            'size_skewness': np.nan,
        }

    d10 = np.percentile(diameters, 10)
    d90 = np.percentile(diameters, 90)
    median = np.median(diameters)

    # Avoid division by zero
    span = (d90 - d10) / median if median != 0 else np.nan

    return {
        'size_mean': np.mean(diameters),
        'size_median': median,
        'size_d10': d10,
        'size_d90': d90,
        'size_span': span,
        'size_skewness': float(skew(diameters)),
    }


def calculate_elongation_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate elongation-related metrics from aspect ratio.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'aspect_ratio' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - elongation_mean: Mean aspect ratio
        - elongation_median: Median aspect ratio
        - elongation_std: Standard deviation of aspect ratio
        - elongation_fraction_gt_2: Fraction of pores with AR > 2.0

    Notes
    -----
    Fraction > 2.0 identifies strongly deformed/elongated pores.
    An aspect ratio of 2.0 means the pore is twice as long as wide.
    """
    aspect_ratios = df['aspect_ratio'].dropna()

    if len(aspect_ratios) == 0:
        logger.warning("No valid aspect ratio values")
        return {
            'elongation_mean': np.nan,
            'elongation_median': np.nan,
            'elongation_std': np.nan,
            'elongation_fraction_gt_2': np.nan,
        }

    n_elongated = np.sum(aspect_ratios > 2.0)
    fraction_gt_2 = n_elongated / len(aspect_ratios)

    return {
        'elongation_mean': np.mean(aspect_ratios),
        'elongation_median': np.median(aspect_ratios),
        'elongation_std': np.std(aspect_ratios),
        'elongation_fraction_gt_2': fraction_gt_2,
    }


def calculate_regularity_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate regularity-related metrics from circularity.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'circularity' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - regularity_mean: Mean circularity
        - regularity_d10: 10th percentile (identifies most irregular pores)

    Notes
    -----
    Circularity = 4 * pi * Area / Perimeter^2
    - Value of 1.0 indicates a perfect circle
    - Lower values indicate more irregular shapes
    D10 identifies the 10% most irregular pores in the distribution.
    """
    circularity = df['circularity'].dropna()

    if len(circularity) == 0:
        logger.warning("No valid circularity values")
        return {
            'regularity_mean': np.nan,
            'regularity_d10': np.nan,
        }

    return {
        'regularity_mean': np.mean(circularity),
        'regularity_d10': np.percentile(circularity, 10),
    }


def calculate_orientation_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate orientation-related metrics from ellipse angle.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'ellipse_angle' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - orientation_entropy: Normalized entropy (0-1 scale)

    Notes
    -----
    Normalized entropy interpretation:
    - 0: Perfect alignment (all pores oriented the same direction)
    - 1: Uniform/isotropic distribution (random orientations)
    Higher values indicate more random/isotropic orientation patterns.
    """
    angles = df['ellipse_angle'].dropna().values

    if len(angles) == 0:
        logger.warning("No valid ellipse angle values")
        return {
            'orientation_entropy': np.nan,
        }

    return {
        'orientation_entropy': calculate_centered_entropy(angles),
    }


def calculate_topology_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate topology-related metrics from coordination number.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'coordination_number' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - topology_cn_mean: Mean coordination number
        - topology_cn_std: Standard deviation of coordination number

    Notes
    -----
    Coordination number represents the number of neighboring pores
    each pore is connected to (based on Voronoi tessellation).
    Higher values indicate more densely packed pore networks.
    """
    coord_numbers = df['coordination_number'].dropna()

    if len(coord_numbers) == 0:
        logger.warning("No valid coordination number values")
        return {
            'topology_cn_mean': np.nan,
            'topology_cn_std': np.nan,
        }

    return {
        'topology_cn_mean': np.mean(coord_numbers),
        'topology_cn_std': np.std(coord_numbers),
    }


def calculate_all_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate all macroscopic metrics for a material.

    Orchestrates calls to individual metric calculation functions.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing individual pore data

    Returns
    -------
    Dict[str, float]
        Combined dictionary of all calculated metrics
    """
    metrics = {}

    # Size metrics (equivalent_diameter)
    metrics.update(calculate_size_metrics(df))

    # Elongation metrics (aspect_ratio)
    metrics.update(calculate_elongation_metrics(df))

    # Regularity metrics (circularity)
    metrics.update(calculate_regularity_metrics(df))

    # Orientation metrics (ellipse_angle)
    metrics.update(calculate_orientation_metrics(df))

    # Topology metrics (coordination_number)
    metrics.update(calculate_topology_metrics(df))

    return metrics


def export_results_to_excel(
    results: List[Dict],
    output_path: Path
) -> Path:
    """
    Export calculated metrics to an Excel file.

    Parameters
    ----------
    results : List[Dict]
        List of dictionaries, each containing metrics for one material
    output_path : Path
        Path for the output Excel file

    Returns
    -------
    Path
        Path to the created Excel file
    """
    # Define column order for output
    column_order = [
        'material_name',
        'n_pores',
        'size_mean',
        'size_median',
        'size_d10',
        'size_d90',
        'size_span',
        'size_skewness',
        'elongation_mean',
        'elongation_median',
        'elongation_std',
        'elongation_fraction_gt_2',
        'regularity_mean',
        'regularity_d10',
        'orientation_entropy',
        'topology_cn_mean',
        'topology_cn_std',
    ]

    df = pd.DataFrame(results)

    # Reorder columns (keep only existing columns in order)
    existing_cols = [c for c in column_order if c in df.columns]
    df = df[existing_cols]

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to Excel
    df.to_excel(output_path, index=False, engine="openpyxl")
    logger.info(f"Results exported to: {output_path}")

    return output_path


def main() -> int:
    """
    Main function to orchestrate macroscopic metrics calculation.

    Returns
    -------
    int
        Exit code (0 for success, 1 for error)
    """
    args = parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    setup_logging(level=log_level)

    logger.info("Starting macroscopic pore metrics calculation")

    # Validate input directory
    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        logger.error(f"Input directory does not exist: {input_dir}")
        return 1

    # Find all analysis reports
    try:
        reports = find_analysis_reports(input_dir)
    except FileNotFoundError as e:
        logger.error(str(e))
        return 1

    if not reports:
        logger.warning(f"No analysis reports found in: {input_dir}")
        return 1

    logger.info(f"Found {len(reports)} material report(s)")

    # Process each material
    results = []
    for material_name, report_path in reports:
        logger.info(f"Processing material: {material_name}")

        df = read_individual_pores_sheet(report_path)
        if df is None:
            continue

        metrics = calculate_all_metrics(df)
        metrics['material_name'] = material_name
        metrics['n_pores'] = len(df)
        results.append(metrics)

        logger.info(
            f"  Processed {len(df)} pores for {material_name}"
        )

    if not results:
        logger.error("No materials were successfully processed")
        return 1

    # Determine output path
    if args.output_file:
        output_path = Path(args.output_file)
    else:
        output_path = input_dir / "macroscopic_pore_metrics.xlsx"

    # Export results
    export_results_to_excel(results, output_path)

    logger.info(
        f"Successfully processed {len(results)} material(s). "
        f"Results saved to: {output_path}"
    )

    return 0


if __name__ == "__main__":
    exit(main())
