"""
Script to calculate macroscopic pore metrics from Excel analysis reports.

This script processes combined analysis reports generated by the batch
quantitative analysis pipeline and calculates aggregate macroscopic
metrics for each material, outputting a single summary Excel file.

Usage:
    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir

    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir \
        --output-file /custom/path/macroscopic_metrics.xlsx

    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir --merge-only
"""
import argparse
import logging
from pathlib import Path

from materials_vision.logging_config import setup_logging
from materials_vision.quantitative_analysis.macroscopic_metrics import (
    calculate_all_metrics,
    export_merged_dataset,
    export_results_to_excel,
    find_analysis_reports,
    generate_material_visualization,
    merge_individual_pores,
    read_individual_pores_sheet,
)

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed command line arguments containing:
        - input_dir: Path to directory containing material subdirectories
        - output_file: Path for output Excel file (optional)
        - verbose: Enable debug logging
    """
    parser = argparse.ArgumentParser(
        description=(
            "Calculate macroscopic pore metrics from analysis reports"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help=(
            "Path to directory containing material subdirectories "
            "with analysis reports"
        )
    )

    parser.add_argument(
        "--output-file",
        type=str,
        default=None,
        help=(
            "Path for output Excel file. Default: "
            "<input_dir>/macroscopic_pore_metrics.xlsx"
        )
    )

    parser.add_argument(
        "--merge-only",
        action="store_true",
        help=(
            "Skip metric calculations and merge all "
            "Individual_Pores sheets into one dataset"
        )
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose (DEBUG) logging"
    )

    parser.add_argument(
        "-p", "--generate-plots",
        action="store_true",
        help="Generate visualization plots for each material"
    )

    return parser.parse_args()


def main() -> int:
    """
    Main function to orchestrate macroscopic metrics calculation.

    Returns
    -------
    int
        Exit code (0 for success, 1 for error)
    """
    args = parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    setup_logging(level=log_level)

    logger.info("Starting macroscopic pore metrics calculation")

    # Validate input directory
    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        logger.error(f"Input directory does not exist: {input_dir}")
        return 1

    # Find all analysis reports
    try:
        reports = find_analysis_reports(input_dir)
    except FileNotFoundError as e:
        logger.error(str(e))
        return 1

    if not reports:
        logger.warning(f"No analysis reports found in: {input_dir}")
        return 1

    logger.info(f"Found {len(reports)} material report(s)")

    # Merge-only mode: combine raw datasets without calculations
    if args.merge_only:
        logger.info("Merge-only mode: combining raw datasets")
        merged_df = merge_individual_pores(reports)
        if merged_df is None:
            logger.error("No data could be merged")
            return 1

        if args.output_file:
            output_path = Path(args.output_file)
        else:
            output_path = (
                input_dir / "merged_individual_pores.xlsx"
            )

        export_merged_dataset(merged_df, output_path)
        logger.info(
            f"Merged {len(merged_df)} pores from "
            f"{merged_df['material_name'].nunique()} material(s). "
            f"Results saved to: {output_path}"
        )
        return 0

    # Process each material
    results = []
    for material_name, report_path in reports:
        logger.info(f"Processing material: {material_name}")

        df = read_individual_pores_sheet(report_path)
        if df is None:
            continue

        metrics = calculate_all_metrics(df)
        metrics['material_name'] = material_name
        metrics['n_pores'] = len(df)
        results.append(metrics)

        logger.info(
            f"  Processed {len(df)} pores for {material_name}"
        )

        # Generate visualization if requested
        if args.generate_plots:
            plot_path = (
                report_path.parent /
                f"{material_name}_macroscopic_visualization.png"
            )
            generate_material_visualization(df, material_name, plot_path)

    if not results:
        logger.error("No materials were successfully processed")
        return 1

    # Determine output path
    if args.output_file:
        output_path = Path(args.output_file)
    else:
        output_path = input_dir / "macroscopic_pore_metrics.xlsx"

    # Export results
    export_results_to_excel(results, output_path)

    logger.info(
        f"Successfully processed {len(results)} material(s). "
        f"Results saved to: {output_path}"
    )

    return 0


if __name__ == "__main__":
    exit(main())
