"""
Script to calculate macroscopic pore metrics from Excel analysis reports.

This script processes combined analysis reports generated by the batch
quantitative analysis pipeline and calculates aggregate macroscopic
metrics for each material, outputting a single summary Excel file.

Usage:
    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir

    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir \
        --output-file /custom/path/macroscopic_metrics.xlsx

    python scripts/quantitative_analysis/calculate_macroscopic_metrics.py \
        --input-dir /path/to/output_dir --merge-only
"""
import argparse
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import entropy, skew

from materials_vision.logging_config import setup_logging

logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    """
    Parse command line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed command line arguments containing:
        - input_dir: Path to directory containing material subdirectories
        - output_file: Path for output Excel file (optional)
        - verbose: Enable debug logging
    """
    parser = argparse.ArgumentParser(
        description=(
            "Calculate macroscopic pore metrics from analysis reports"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--input-dir",
        type=str,
        required=True,
        help=(
            "Path to directory containing material subdirectories "
            "with analysis reports"
        )
    )

    parser.add_argument(
        "--output-file",
        type=str,
        default=None,
        help=(
            "Path for output Excel file. Default: "
            "<input_dir>/macroscopic_pore_metrics.xlsx"
        )
    )

    parser.add_argument(
        "--merge-only",
        action="store_true",
        help=(
            "Skip metric calculations and merge all "
            "Individual_Pores sheets into one dataset"
        )
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose (DEBUG) logging"
    )

    parser.add_argument(
        "-p", "--generate-plots",
        action="store_true",
        help="Generate visualization plots for each material"
    )

    return parser.parse_args()


def find_analysis_reports(input_dir: Path) -> List[Tuple[str, Path]]:
    """
    Find all combined analysis report Excel files in the input directory.

    Searches for files matching the pattern:
    <input_dir>/<material_name>/reports/*_combined_analysis_report.xlsx

    Parameters
    ----------
    input_dir : Path
        Parent directory containing material subdirectories

    Returns
    -------
    List[Tuple[str, Path]]
        List of tuples containing (material_name, report_path)

    Raises
    ------
    FileNotFoundError
        If input_dir does not exist
    """
    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")

    reports = []

    subdirs = [
        d for d in input_dir.iterdir()
        if d.is_dir() and not d.name.startswith('.')
    ]
    subdirs.sort()

    for subdir in subdirs:
        reports_dir = subdir / "reports"
        if not reports_dir.exists():
            logger.debug(f"No reports directory in: {subdir.name}")
            continue

        report_files = [
            f for f in reports_dir.glob("*_combined_analysis_report.xlsx")
            if not f.name.startswith('.')
        ]

        if not report_files:
            logger.debug(
                f"No analysis report found in: {reports_dir}"
            )
            continue

        report_path = report_files[0]
        material_name = subdir.name
        reports.append((material_name, report_path))
        logger.info(f"Found report for material: {material_name}")

    return reports


def read_individual_pores_sheet(
    report_path: Path
) -> Optional[pd.DataFrame]:
    """
    Read the Individual_Pores sheet from an analysis report.

    Parameters
    ----------
    report_path : Path
        Path to the Excel analysis report

    Returns
    -------
    Optional[pd.DataFrame]
        DataFrame with individual pore data, or None if reading fails

    Notes
    -----
    Required columns: equivalent_diameter, aspect_ratio, circularity,
    ellipse_angle, coordination_number
    """
    required_columns = [
        'equivalent_diameter',
        'aspect_ratio',
        'circularity',
        'ellipse_angle',
        'coordination_number'
    ]

    try:
        df = pd.read_excel(
            report_path,
            sheet_name="Individual_Pores",
            engine="openpyxl"
        )
    except Exception as e:
        logger.error(f"Failed to read {report_path}: {e}")
        return None

    if df.empty:
        logger.warning(f"No pore data in {report_path}")
        return None

    missing_cols = [c for c in required_columns if c not in df.columns]
    if missing_cols:
        logger.warning(
            f"Missing columns in {report_path.name}: {missing_cols}. "
            "Skipping this material."
        )
        return None

    return df


def calculate_centered_entropy(
    angles: np.ndarray,
    num_bins: int = 18
) -> float:
    """
    Calculate normalized entropy of orientation angles.

    Centers the angle distribution around its mean direction before
    computing entropy, providing a rotation-invariant measure of
    orientation uniformity.

    Parameters
    ----------
    angles : np.ndarray
        Array of orientation angles in degrees (0-180)
    num_bins : int, optional
        Number of histogram bins for entropy calculation (default: 18)

    Returns
    -------
    float
        Normalized entropy value between 0 and 1, where:
        - 0 indicates perfect alignment (all angles identical)
        - 1 indicates uniform distribution (isotropic)

    Notes
    -----
    The function uses circular statistics to handle the periodic nature
    of orientation data. Angles are doubled before averaging to account
    for the 180-degree symmetry of ellipse orientations.

    Formula for normalization: H_norm = H / H_max
    where H_max = ln(num_bins) for uniform distribution
    """
    angles = np.array(angles)

    # Handle NaN values
    angles = angles[~np.isnan(angles)]
    if len(angles) == 0:
        return np.nan

    # Convert to radians and double (orientation is pi-periodic)
    angles_rad = np.deg2rad(angles) * 2

    # Calculate mean direction using circular statistics
    sin_sum = np.sum(np.sin(angles_rad))
    cos_sum = np.sum(np.cos(angles_rad))
    mean_angle = np.rad2deg(np.arctan2(sin_sum, cos_sum)) / 2

    # Center distribution around mean (shift so mean is at 90 degrees)
    shift = 90 - mean_angle
    angles_shifted = (angles + shift) % 180

    # Calculate histogram and entropy
    counts, _ = np.histogram(angles_shifted, bins=num_bins, range=(0, 180))
    if counts.sum() == 0:
        return 0.0

    probs = counts / counts.sum()
    shannon_entropy = entropy(probs)  # Uses natural log by default
    max_entropy = np.log(num_bins)

    return shannon_entropy / max_entropy


def calculate_size_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate size-related metrics from equivalent diameter.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'equivalent_diameter' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - size_mean: Mean equivalent diameter
        - size_median: Median equivalent diameter
        - size_d10: 10th percentile
        - size_d90: 90th percentile
        - size_span: (D90 - D10) / Median
        - size_skewness: Skewness of size distribution

    Notes
    -----
    Span formula: (D90 - D10) / D50
    This is a common metric in particle size analysis describing
    the width of the size distribution relative to the median.
    """
    diameters = df['equivalent_diameter'].dropna()

    if len(diameters) == 0:
        logger.warning("No valid diameter values")
        return {
            'size_mean': np.nan,
            'size_median': np.nan,
            'size_d10': np.nan,
            'size_d90': np.nan,
            'size_span': np.nan,
            'size_skewness': np.nan,
        }

    d10 = np.percentile(diameters, 10)
    d90 = np.percentile(diameters, 90)
    median = np.median(diameters)

    # Avoid division by zero
    span = (d90 - d10) / median if median != 0 else np.nan

    return {
        'size_mean': np.mean(diameters),
        'size_median': median,
        'size_d10': d10,
        'size_d90': d90,
        'size_span': span,
        'size_skewness': float(skew(diameters)),
    }


def calculate_elongation_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate elongation-related metrics from aspect ratio.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'aspect_ratio' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - elongation_mean: Mean aspect ratio
        - elongation_median: Median aspect ratio
        - elongation_std: Standard deviation of aspect ratio
        - elongation_fraction_gt_2: Fraction of pores with AR > 2.0

    Notes
    -----
    Fraction > 2.0 identifies strongly deformed/elongated pores.
    An aspect ratio of 2.0 means the pore is twice as long as wide.
    """
    aspect_ratios = df['aspect_ratio'].dropna()

    if len(aspect_ratios) == 0:
        logger.warning("No valid aspect ratio values")
        return {
            'elongation_mean': np.nan,
            'elongation_median': np.nan,
            'elongation_std': np.nan,
            'elongation_fraction_gt_2': np.nan,
        }

    n_elongated = np.sum(aspect_ratios > 2.0)
    fraction_gt_2 = n_elongated / len(aspect_ratios)

    return {
        'elongation_mean': np.mean(aspect_ratios),
        'elongation_median': np.median(aspect_ratios),
        'elongation_std': np.std(aspect_ratios),
        'elongation_fraction_gt_2': fraction_gt_2,
    }


def calculate_regularity_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate regularity-related metrics from circularity.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'circularity' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - regularity_mean: Mean circularity
        - regularity_d10: 10th percentile (identifies most irregular pores)

    Notes
    -----
    Circularity = 4 * pi * Area / Perimeter^2
    - Value of 1.0 indicates a perfect circle
    - Lower values indicate more irregular shapes
    D10 identifies the 10% most irregular pores in the distribution.
    """
    circularity = df['circularity'].dropna()

    if len(circularity) == 0:
        logger.warning("No valid circularity values")
        return {
            'regularity_mean': np.nan,
            'regularity_d10': np.nan,
        }

    return {
        'regularity_mean': np.mean(circularity),
        'regularity_d10': np.percentile(circularity, 10),
    }


def calculate_orientation_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate orientation-related metrics from ellipse angle.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'ellipse_angle' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - orientation_entropy: Normalized entropy (0-1 scale)

    Notes
    -----
    Normalized entropy interpretation:
    - 0: Perfect alignment (all pores oriented the same direction)
    - 1: Uniform/isotropic distribution (random orientations)
    Higher values indicate more random/isotropic orientation patterns.
    """
    angles = df['ellipse_angle'].dropna().values

    if len(angles) == 0:
        logger.warning("No valid ellipse angle values")
        return {
            'orientation_entropy': np.nan,
        }

    return {
        'orientation_entropy': calculate_centered_entropy(angles),
    }


def calculate_topology_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate topology-related metrics from coordination number.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing 'coordination_number' column

    Returns
    -------
    Dict[str, float]
        Dictionary containing:
        - topology_cn_mean: Mean coordination number
        - topology_cn_std: Standard deviation of coordination number

    Notes
    -----
    Coordination number represents the number of neighboring pores
    each pore is connected to (based on Voronoi tessellation).
    Higher values indicate more densely packed pore networks.
    """
    coord_numbers = df['coordination_number'].dropna()

    if len(coord_numbers) == 0:
        logger.warning("No valid coordination number values")
        return {
            'topology_cn_mean': np.nan,
            'topology_cn_std': np.nan,
        }

    return {
        'topology_cn_mean': np.mean(coord_numbers),
        'topology_cn_std': np.std(coord_numbers),
    }


def merge_individual_pores(
    reports: List[Tuple[str, Path]]
) -> Optional[pd.DataFrame]:
    """
    Merge Individual_Pores sheets from all materials into one DataFrame.

    Parameters
    ----------
    reports : List[Tuple[str, Path]]
        List of (material_name, report_path) tuples

    Returns
    -------
    Optional[pd.DataFrame]
        Combined DataFrame with a 'material_name' column,
        or None if no data could be read
    """
    frames = []
    for material_name, report_path in reports:
        df = read_individual_pores_sheet(report_path)
        if df is None:
            continue
        df = df.copy()
        df.insert(0, 'material_name', material_name)
        frames.append(df)
        logger.info(
            f"  Loaded {len(df)} pores from {material_name}"
        )

    if not frames:
        return None

    merged = pd.concat(frames, ignore_index=True)
    logger.info(
        f"Merged dataset: {len(merged)} total pores "
        f"from {len(frames)} material(s)"
    )
    return merged


def export_merged_dataset(
    df: pd.DataFrame,
    output_path: Path
) -> Path:
    """
    Export merged individual pores dataset to Excel.

    Parameters
    ----------
    df : pd.DataFrame
        Merged DataFrame with all individual pore data
    output_path : Path
        Path for the output Excel file

    Returns
    -------
    Path
        Path to the created Excel file
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(output_path, index=False, engine="openpyxl")
    logger.info(f"Merged dataset exported to: {output_path}")
    return output_path


def calculate_all_metrics(df: pd.DataFrame) -> Dict[str, float]:
    """
    Calculate all macroscopic metrics for a material.

    Orchestrates calls to individual metric calculation functions.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing individual pore data

    Returns
    -------
    Dict[str, float]
        Combined dictionary of all calculated metrics
    """
    metrics = {}

    # Size metrics (equivalent_diameter)
    metrics.update(calculate_size_metrics(df))

    # Elongation metrics (aspect_ratio)
    metrics.update(calculate_elongation_metrics(df))

    # Regularity metrics (circularity)
    metrics.update(calculate_regularity_metrics(df))

    # Orientation metrics (ellipse_angle)
    metrics.update(calculate_orientation_metrics(df))

    # Topology metrics (coordination_number)
    metrics.update(calculate_topology_metrics(df))

    return metrics


def plot_orientation_rose(
    ax: plt.Axes,
    angles: np.ndarray,
    num_bins: int = 36
) -> None:
    """
    Create polar rose plot with correct bin centering.

    Parameters
    ----------
    ax : plt.Axes
        Matplotlib polar axes to plot on
    angles : np.ndarray
        Array of orientation angles in degrees (-90 to 90)
    num_bins : int, optional
        Number of bins for the histogram (default: 36, i.e. 5 deg per bin)

    Notes
    -----
    CRITICAL: 0 degrees is positioned at 3 o'clock (East).
    Bins are centered using (edge_left + edge_right) / 2.
    The plot mirrors the -90 to 90 range to create a full 360 degree view.
    """
    angles = np.array(angles)
    angles = angles[~np.isnan(angles)]

    if len(angles) == 0:
        return

    # Compute histogram with range -90 to 90
    counts, bin_edges = np.histogram(angles, bins=num_bins, range=(-90, 90))

    # Calculate bin CENTERS: (left_edge + right_edge) / 2
    bin_centers_deg = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Convert to radians
    bin_centers_rad = np.deg2rad(bin_centers_deg)

    # Duplicate for 180-degree symmetry (ellipse orientation is symmetric)
    theta = np.concatenate([bin_centers_rad, bin_centers_rad + np.pi])
    radii = np.concatenate([counts, counts])

    # Bar width in radians (bins touch each other)
    width = np.deg2rad(180 / num_bins)

    # Plot bars
    ax.bar(
        theta, radii, width=width, bottom=0.0,
        color='#457b9d', alpha=0.8, edgecolor='white', linewidth=0.5
    )

    # Set 0 degrees at 3 o'clock (East), counterclockwise direction
    ax.set_theta_zero_location('E')
    ax.set_theta_direction(1)

    ax.set_title("Orientation Rose Plot", fontsize=10, pad=15)


def generate_material_visualization(
    df: pd.DataFrame,
    material_name: str,
    output_path: Path
) -> Path:
    """
    Generate a 3x2 grid visualization for a material's pore analysis.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing individual pore data
    material_name : str
        Name of the material for the title
    output_path : Path
        Path to save the output figure

    Returns
    -------
    Path
        Path to the saved figure

    Notes
    -----
    Layout:
    - Row 1: Network Topology (coordination_number), Size Distribution
    - Row 2: Elongation Degree (aspect_ratio), Shape Quality scatter
    - Row 3: Linear Orientation Histogram, Polar Rose Plot
    """
    sns.set_style("whitegrid")

    # Create figure with 3x2 grid, last subplot is polar
    fig = plt.figure(figsize=(14, 12))

    # Row 1, Col 1: Network Topology - coordination_number histogram
    ax1 = fig.add_subplot(3, 2, 1)
    coord_data = df['coordination_number'].dropna()
    if len(coord_data) > 0:
        sns.histplot(
            coord_data, ax=ax1, kde=False, color='teal',
            edgecolor='black', linewidth=0.5
        )
    ax1.set_xlabel("Coordination Number")
    ax1.set_ylabel("Frequency")
    ax1.set_title("Network Topology")

    # Row 1, Col 2: Size Distribution - equivalent_diameter KDE filled
    ax2 = fig.add_subplot(3, 2, 2)
    diameter_data = df['equivalent_diameter'].dropna()
    if len(diameter_data) > 0:
        sns.kdeplot(
            diameter_data, ax=ax2, color='steelblue',
            fill=True, alpha=0.6, linewidth=2
        )
        median_val = np.median(diameter_data)
        ax2.axvline(
            median_val, color='red', linestyle='--', linewidth=2,
            label=f'Median: {median_val:.1f}'
        )
        ax2.legend()
    ax2.set_xlabel("Equivalent Diameter (um)")
    ax2.set_ylabel("Density")
    ax2.set_title("Size Distribution")

    # Row 2, Col 1: Elongation Degree - aspect_ratio KDE filled
    ax3 = fig.add_subplot(3, 2, 3)
    ar_data = df['aspect_ratio'].dropna()
    if len(ar_data) > 0:
        sns.kdeplot(
            ar_data, ax=ax3, color='darkorange',
            fill=True, alpha=0.6, linewidth=2
        )
        ax3.axvline(
            2.0, color='red', linestyle='--', linewidth=2,
            label='Threshold: 2.0'
        )
        ax3.legend()
    ax3.set_xlabel("Aspect Ratio")
    ax3.set_ylabel("Density")
    ax3.set_title("Elongation Degree")

    # Row 2, Col 2: Shape Quality - overlapped KDE for circularity & solidity
    ax4 = fig.add_subplot(3, 2, 4)
    circ_data = df['circularity'].dropna()
    solid_data = df['solidity'].dropna() if 'solidity' in df.columns else None
    if len(circ_data) > 0:
        sns.kdeplot(
            circ_data, ax=ax4, color='purple',
            fill=True, alpha=0.5, linewidth=2, label='Circularity'
        )
    if solid_data is not None and len(solid_data) > 0:
        sns.kdeplot(
            solid_data, ax=ax4, color='teal',
            fill=True, alpha=0.5, linewidth=2, label='Solidity'
        )
    ax4.set_xlabel("Value")
    ax4.set_ylabel("Density")
    ax4.set_title("Shape Quality")
    ax4.set_xlim(0, 1.1)
    ax4.legend()

    # Row 3, Col 1: Linear Orientation Histogram (-90 to 90 range)
    ax5 = fig.add_subplot(3, 2, 5)
    angle_data = df['ellipse_angle'].dropna()
    if len(angle_data) > 0:
        sns.histplot(
            angle_data, ax=ax5, bins=36, kde=False, color='forestgreen',
            edgecolor='black', linewidth=0.5
        )
    ax5.set_xlabel("Ellipse Angle (degrees)")
    ax5.set_ylabel("Frequency")
    ax5.set_title("Orientation Distribution (Linear)")
    ax5.set_xlim(-90, 90)
    ax5.axvline(0, color='red', linestyle='--', linewidth=1, alpha=0.7)

    # Row 3, Col 2: Polar Rose Plot
    ax6 = fig.add_subplot(3, 2, 6, projection='polar')
    if len(angle_data) > 0:
        plot_orientation_rose(ax6, angle_data.values)

    # Overall title
    fig.suptitle(
        f"Macroscopic Pore Analysis: {material_name}",
        fontsize=14, fontweight='bold', y=0.98
    )

    plt.tight_layout(rect=[0, 0, 1, 0.96])

    # Save figure
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close(fig)

    logger.info(f"Visualization saved to: {output_path}")
    return output_path


def export_results_to_excel(
    results: List[Dict],
    output_path: Path
) -> Path:
    """
    Export calculated metrics to an Excel file.

    Parameters
    ----------
    results : List[Dict]
        List of dictionaries, each containing metrics for one material
    output_path : Path
        Path for the output Excel file

    Returns
    -------
    Path
        Path to the created Excel file
    """
    # Define column order for output
    column_order = [
        'material_name',
        'n_pores',
        'size_mean',
        'size_median',
        'size_d10',
        'size_d90',
        'size_span',
        'size_skewness',
        'elongation_mean',
        'elongation_median',
        'elongation_std',
        'elongation_fraction_gt_2',
        'regularity_mean',
        'regularity_d10',
        'orientation_entropy',
        'topology_cn_mean',
        'topology_cn_std',
    ]

    df = pd.DataFrame(results)

    # Reorder columns (keep only existing columns in order)
    existing_cols = [c for c in column_order if c in df.columns]
    df = df[existing_cols]

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to Excel
    df.to_excel(output_path, index=False, engine="openpyxl")
    logger.info(f"Results exported to: {output_path}")

    return output_path


def main() -> int:
    """
    Main function to orchestrate macroscopic metrics calculation.

    Returns
    -------
    int
        Exit code (0 for success, 1 for error)
    """
    args = parse_args()

    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    setup_logging(level=log_level)

    logger.info("Starting macroscopic pore metrics calculation")

    # Validate input directory
    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        logger.error(f"Input directory does not exist: {input_dir}")
        return 1

    # Find all analysis reports
    try:
        reports = find_analysis_reports(input_dir)
    except FileNotFoundError as e:
        logger.error(str(e))
        return 1

    if not reports:
        logger.warning(f"No analysis reports found in: {input_dir}")
        return 1

    logger.info(f"Found {len(reports)} material report(s)")

    # Merge-only mode: combine raw datasets without calculations
    if args.merge_only:
        logger.info("Merge-only mode: combining raw datasets")
        merged_df = merge_individual_pores(reports)
        if merged_df is None:
            logger.error("No data could be merged")
            return 1

        if args.output_file:
            output_path = Path(args.output_file)
        else:
            output_path = (
                input_dir / "merged_individual_pores.xlsx"
            )

        export_merged_dataset(merged_df, output_path)
        logger.info(
            f"Merged {len(merged_df)} pores from "
            f"{merged_df['material_name'].nunique()} material(s). "
            f"Results saved to: {output_path}"
        )
        return 0

    # Process each material
    results = []
    for material_name, report_path in reports:
        logger.info(f"Processing material: {material_name}")

        df = read_individual_pores_sheet(report_path)
        if df is None:
            continue

        metrics = calculate_all_metrics(df)
        metrics['material_name'] = material_name
        metrics['n_pores'] = len(df)
        results.append(metrics)

        logger.info(
            f"  Processed {len(df)} pores for {material_name}"
        )

        # Generate visualization if requested
        if args.generate_plots:
            plot_path = (
                report_path.parent /
                f"{material_name}_macroscopic_visualization.png"
            )
            generate_material_visualization(df, material_name, plot_path)

    if not results:
        logger.error("No materials were successfully processed")
        return 1

    # Determine output path
    if args.output_file:
        output_path = Path(args.output_file)
    else:
        output_path = input_dir / "macroscopic_pore_metrics.xlsx"

    # Export results
    export_results_to_excel(results, output_path)

    logger.info(
        f"Successfully processed {len(results)} material(s). "
        f"Results saved to: {output_path}"
    )

    return 0


if __name__ == "__main__":
    exit(main())
